"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { patrickHandSc, Inria } from "../utils/font";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-800 ${geistSans.variable} ${geistMono.variable} antialiased bg-cover bg-center bg-no-repeat bg-fixed`}
        // style={{ backgroundImage: "url(images/Sora.webp)" }}
      >
        <nav
          className={`${patrickHandSc.className}  bg-white bg-opacity-15 backdrop-filter backdrop-blur-md p-4`}
        >
          <ul className="flex justify-between items-center text-2xl">
            <Link href="/" className="text-white hover:text-gray-400">
              Home
            </Link>
            <div className="flex space-x-6 sm:space-x-8 md:space-x-10 lg:space-x-16">
              <Link
                href="/experience"
                className="text-white hover:text-gray-400"
              >
                Experience
              </Link>
              <Link href="/projects" className="text-white hover:text-gray-400">
                Project/Coursework
              </Link>

              <li>
                <a href="/other" className="text-white hover:text-gray-400">
                  Other
                </a>
              </li>
            </div>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
